STALL_MAPPING = {
    "HARD_LUMPS": 0,
    "LUMPY_SAUSAGE": 1,
    "CRACKED_SAUSAGE": 2,
    "SMOOTH_SAUSAGE": 3,
    "SOFT_BLOBS": 4,
    "MUSHY_SUBSTANCE": 5,
    "LIQUID_FUCKED_UP": 6,
    "DIE": 7  # JUST FINISH WITH EVERYTHING ALREADY
}